# Generated by Django 5.2.11 on 2026-05-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the question.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='The description of the question.', null=True)),
                ('slug', models.SlugField(help_text='The slug of the question.', unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
    ]
