# Generated by Django 5.2.11 on 2026-03-01 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the question.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='The description of the question.', null=True)),
                ('slug', models.SlugField(help_text='The slug of the question.', unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the question was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the question was last updated.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the question is active or not.')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ManyToManyField(help_text='The tags of the question.', related_name='questions', to='tags.tag')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['-created_at'],
            },
        ),
    ]
