# Generated by Django 5.2.11 on 2026-03-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tag',
            field=models.ManyToManyField(blank=True, help_text='The tags of the question.', related_name='questions', to='tags.tag'),
        ),
    ]
