# Generated by Django 5.2.11 on 2026-05-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='The slug of the tag.', unique=True),
        ),
    ]
