# Generated by Django 5.2.11 on 2026-05-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
